config/routes.rb
Rails.application.routes.draw do

  root 'subs#index'

  resources :users do
    resources :subs, only: [:new]
  end

  resources :subs, only: [:index, :create, :edit, :update, :show] do
    resources :posts, only: [:new]
  end

  resources :posts, only: [:create, :edit, :update, :show, :destroy] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show, :destroy]

  resource  :session, only: [:new, :create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :user_id, :post_id, :content, presence: true
  validate  :ensure_user_exists, :ensure_post_exists

  belongs_to :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  belongs_to :post

  has_many :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id

  def top_level_parent
    return self if parent_comment_id == nil
    Comment.find(self.parent_comment_id).top_level_parent
  end

  def ensure_user_exists
    unless User.find(user_id)
      comment.errors[:user_id] << "User id must be valid!"
    end
  end

  def ensure_post_exists
    unless Post.find(post_id)
      comment.errors[:post_id] << "Post id must be valid!"
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :user_id, presence: true
  validate :content_or_url
  validate :sub_exists
  validate :user_exists

  belongs_to :author,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id

  has_many :post_subs, inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments

  def content_or_url
    if url.empty? && content.empty?
      self.errors[:content] << "Must provide content or URL"
    end
  end

  def sub_exists
    unless subs.size > 0
      self.errors[:sub_id] << "Must have one sub!"
    end
  end

  def user_exists
    unless User.find(user_id)
      self.errors[:user_id] << "User id must be valid!"
    end
  end

end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true
  
  belongs_to :post

  belongs_to :sub

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true
  validate :ensure_user_exists

  belongs_to :moderator,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  has_many :post_subs, inverse_of: :sub

  has_many :posts,
    through: :post_subs,
    source: :post

  def ensure_user_exists
    unless User.find(user_id)
      sub.errors[:user_id] << "User id must be valid!"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :subs,
    class_name: "Sub",
    foreign_key: :user_id,
    primary_key: :id

  has_many :posts,
    class_name: 'Post',
    foreign_key: :user_id,
    primary_key: :id

  has_many :comments, inverse_of: :author

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def password
    @password
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to comment_url(@comment.top_level_parent)
    else
      render :new
    end
  end

  def destroy
  end

private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :user_is_author, only: [:edit, :update]
  before_action :user_is_authorized, only: [:destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def edit
    @post ||= Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end

  def user_is_author
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      redirect_to subs_url
    end
  end

  def user_is_authorized
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id ||
           current_user.id == @post.sub.moderator.id
      redirect_to post_url(@post.id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :url, sub_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to user_url(current_user) if logged_in?
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:password])
    if @user
      session[:session_token] = @user.reset_session_token!
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    session[:session_token] = nil
    @user = User.new
    render :new
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_sub_owner, only: [:edit]

  def new
    @sub = Sub.new
  end

  def index
    @subs = Sub.all
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub ||= Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.update(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  def require_sub_owner
    @sub = Sub.find(params[:id])
    unless current_user.id == @sub.user_id
      redirect_to
      sub_url(@sub)
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
      session[:session_token] = @user.session_token
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user ||= User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input type="hidden" value="#{form_authenticity_token}"
             name="authenticity_token">
    HTML
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<form action="<%= url %>" method="POST">
  <input type="hidden" value="<%= post_id %>" name="comment[post_id]">
  <input type="hidden" value="<%= parent_comment_id %>"
         name="comment[parent_comment_id]">
  <%= auth_token %>
  <p>
    <label>New comment:
      <textarea name="comment[content]"><%= comment.content %></textarea>
    </label>
  </p>

  <p>
    <button value="submit">Submit</button>
  </p>
</form>

app/views/comments/_show.html.erb
<p>
  <%= comment.content %>
</p>
- <%= comment.author.email %>

<%= render "comments/comment", url: comments_url, parent_comment_id: comment.id,
  post_id: post_id, comment: comment %>

<ul>
<% Comment.where(parent_comment_id: comment.id).each do |subcomment| %>
  <%= render 'show', comment: subcomment, post_id: post_id %>
<% end %>
</ul>

app/views/comments/show.html.erb
<p>
  <%= @comment.content %>
</p>
- <%= @comment.author.email %>

<%= render "comments/comment", url: comments_url, parent_comment_id: @comment.id,
  post_id: @post.id, comment: @comment %>
  
<ul>
<% Comment.where(parent_comment_id: @comment.id).each do |comment| %>
  <%= render 'show', comment: comment, post_id: @post.id %>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    welcome, <%= current_user.email %>!
      <form action="<%= session_url %>" method="POST">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <button value="submit">log out</button>
      </form>
  <% else %>
    <a href="<%= new_session_url %>">Log in</a> |
    <a href="<%= new_user_url %>">Sign up</a> |
  <% end %>
<a href="<%= subs_url %>">All Subs!</a>
<hr>
  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% sub_id ||= 0 %>
<form action="<%= url %>" method="POST">
  <input type="hidden" value="<%= method %>" name="_method">
  <%= auth_token %>

    <% Sub.all.each do |sub| %>
    <input type="hidden" name="post[sub_ids][]" value="">
        <label><%= sub.title %>
          <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
                 <%= "checked" if sub_id == sub.id ||
                     post.sub_ids.include?(sub.id) %>>
        </label>
    <% end %>

  <p>
    <label>Title:
      <input type="text" name="post[title]" value="<%= post.title %>">
    </label>
  </p>

  <p>
    <label>URL:
      <input type="text" name="post[url]" value="<%= post.url %>">
    </label>
  </p>

  <p>
    <label>Content:
      <textarea name="post[content]"><%= post.content %></textarea>
    </label>
  </p>

  <p>
    <button value="submit">Submit</button>
  </p>
</form>

app/views/posts/edit.html.erb
<h1> Edit post </h1>

<%= render 'form',
    post: @post,
    url: post_url(@post),
    method: "PATCH" %>

app/views/posts/new.html.erb
<h1> New post </h1>

<%= render 'form',
    post: @post,
    url: posts_url,
    method: "POST",
    sub_id: params[:id] %>

app/views/posts/show.html.erb
<a href="<%= @post.url %>"><h2> <%= @post.title %> </h2></a>
<p>
  <%= @post.content %>
</p>
<% if current_user.id == @post.user_id %>
<p>
  <a href="<%= edit_post_url(@post.id) %>">Edit post</a>
</p>
<p>
  <form action="<%= post_url(@post.id) %>" method="POST">
    <input type="hidden" value="DELETE" name="_method">
    <%= auth_token %>
    <button value="submit">Delete</button>
  </form>
</p>
<% end %>
<p>
  Comments:
</p>

<%= render "comments/comment", url: comments_url, parent_comment_id: nil,
    post_id: @post.id, comment: @comment %>
<% Comment.where(post_id: @post.id).where(parent_comment_id: nil).each do |comment| %>
  <p>
    <%= comment.content %><br>
    <a href="<%= comment_url(comment.id) %>">View Thread</a>
  </p>
<% end %>

app/views/subs/_form.html.erb
<form action="<%= url %>" method="POST">
  <input type="hidden" value="<%= method %>" name="_method">
  <%= auth_token %>
  <p>
    <label>Title:
      <input type="text" name="sub[title]" value="<%= sub.title %>">
    </label>
  </p>

  <p>
    <label>Description:
      <textarea name="sub[description]"><%= sub.description %></textarea>
    </label>
  </p>

  <p>
    <button value="submit">Submit</button>
  </p>
</form>

app/views/subs/edit.html.erb
<h1> Edit sub </h1>

<%= render 'form', sub: @sub, url: sub_url(@sub), method: "PATCH" %>

app/views/subs/index.html.erb
<h1> All Subs!!11 </h1>

<% Sub.all.each do |sub| %>

  <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <br>

<% end %>
<% if logged_in? %>
  <p>
    <a href="<%=new_user_sub_url(current_user.id)%>">New Sub!</a>
  </p>
<% end %>

app/views/subs/new.html.erb
<h1>New Sub!!</h1>

<%= render 'form', sub: @sub, url: subs_url, method: "POST" %>

app/views/subs/show.html.erb
<h1>Welcome to the <%= @sub.title %> sub!</h1>

<% if current_user.id == @sub.user_id %>
<p>
  <a href="<%= edit_sub_url(@sub) %>">Edit</a>
</p>
<% end %>
<p>
  <%= @sub.description %>
</p>
<p>
  <a href="<%= new_sub_post_url(@sub.id) %>">New post</a>
</p>
<% @sub.posts.each do |post| %>
<p>
  <li><a href=" <%= post_url(post.id) %>"><%= post.title %></a></li>
</p>
<% end %>

app/views/users/_form.html.erb
<form action="<%= url %>" method="POST">
  <input type="hidden" value="<%= method %>" name="_method">

  <%= auth_token %>
  <label>Email:
    <input type="text" name="user[email]" value="<%= user.email %>">
  </label>

  <label>Password:
    <input type="password" name="user[password]">
  </label>

  <button value="submit">Submit</button>

</form>

app/views/users/edit.html.erb
<h1> Edit profile </h1>

<%= render 'form', user: @user, url: user_url(@user), method: "PATCH" %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render 'form', user: @user, url: users_url, method: "POST" %>

app/views/users/show.html.erb
<h1> Welcome, <%= @user.email %>!</h1>